<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-14</name>
   <tag></tag>
   <elementGuidId>7d0de2b3-bbcc-4a9e-95d6-1a39857d09e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ac66848-96ee-44cd-a301-510b0108b7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bff22762-f9e8-4bf2-ae3c-20d4aab126c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>fe78412a-f91b-49fd-bd6a-5cff29fa3394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>3633518d-b562-43bc-9441-d6342d6a8218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  email </value>
      <webElementGuid>b789bde9-d9b5-4d9f-910d-5c67c87cea4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-14&quot;)</value>
      <webElementGuid>5f6ef78a-16ec-4292-bb05-b3a1a2c0e3d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-14']</value>
      <webElementGuid>39ca6952-b983-4d0c-8f66-6c32d4074735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-14']/input</value>
      <webElementGuid>f2a5d2a1-e785-497b-8242-e37358f71a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>bda1e0f5-79a5-4f8d-a7b7-ea00fef9e038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'vfb-14' and @id = 'vfb-14']</value>
      <webElementGuid>b11bea88-1e2b-45a3-980d-3809753691af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
