<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selenium WebDriver_vfb-20</name>
   <tag></tag>
   <elementGuidId>6e4c488d-a708-40fc-9c9d-32adea8eab18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-20-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-20-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb9545a8-264e-48a4-a6ef-f1bb9eba1770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>261fd1de-5667-4298-9b99-c73f121e700d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-20[]</value>
      <webElementGuid>c7cd0ed7-6a49-40fe-96f1-734a08488280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-20-1</value>
      <webElementGuid>3c472e3c-9477-4bf8-95e3-abf335add8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UFT</value>
      <webElementGuid>fb7b10b9-bfb7-4c16-a064-392f8af2d20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-checkbox  </value>
      <webElementGuid>a5a00f8e-f0e7-427c-a3d1-0bc998c84f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-20-1&quot;)</value>
      <webElementGuid>784c4744-891b-4418-b417-12dd5b8df862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-20-1']</value>
      <webElementGuid>271ae3f2-b870-41fb-9177-4c4de1ab5ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-20']/div/span[2]/input</value>
      <webElementGuid>7449f29a-3f9a-4300-aaec-81f930379544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/span[2]/input</value>
      <webElementGuid>72677333-be65-4a6f-a8a8-023819263508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vfb-20[]' and @id = 'vfb-20-1']</value>
      <webElementGuid>8cc2f7b7-046a-4d00-baf5-1e2a83ea6802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
