<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mobile Number</name>
   <tag></tag>
   <elementGuidId>ac4e39c7-ad05-4b4c-9ed8-3e5e037786ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>52807e10-0d3b-4ffb-9a30-5f84160f4e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-item vfb-item-number  </value>
      <webElementGuid>b2d0a470-3e65-4a97-a6f0-240cdf7b2378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-vfb-19</value>
      <webElementGuid>d9b3b9f2-107a-4ab0-b2f5-8c5ddb8f0323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Number </value>
      <webElementGuid>a59bf422-fd07-42d0-a887-90dae9499b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-19&quot;)</value>
      <webElementGuid>2d356e01-70aa-418b-a93e-0be2c8febea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-19']</value>
      <webElementGuid>cf75a3ad-a953-4d71-8baf-8665c5130da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-1']/ul/li[8]</value>
      <webElementGuid>3a9ea54f-f341-43cc-9293-a4b5be679ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM'])[1]/following::li[1]</value>
      <webElementGuid>d8949d45-ffa5-420e-939b-2c58c1fbebf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HH'])[1]/following::li[1]</value>
      <webElementGuid>3b1ba398-1209-4d30-b5a1-d2975fa1389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Interested'])[1]/preceding::li[1]</value>
      <webElementGuid>da1d5571-2c6c-4523-9433-e5a15975aa16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ul/li[8]</value>
      <webElementGuid>f2f915a9-94e0-45b9-84f0-5a56b044cf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'item-vfb-19' and (text() = 'Mobile Number ' or . = 'Mobile Number ')]</value>
      <webElementGuid>1af8c555-7791-4b3c-b44d-bad9b7dc6bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
