<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thailand</name>
   <tag></tag>
   <elementGuidId>24fb3488-8c5f-4900-852d-21bb2dd9be49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-vfb-13-country-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-vfb-13-country-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d08a4ba8-43a4-4a0d-950d-95b83c113eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>cb267f15-cb33-4e58-b8ad-211514a011c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vfb-13-country-container</value>
      <webElementGuid>48cf1489-ad9b-4930-8de6-65fa3362b30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ee7b83bf-049c-46a5-87e5-7e873a0f5e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61f6b629-0b19-4fe5-a42d-44c61fb910ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thailand</value>
      <webElementGuid>1d2b43fc-f4e9-4eef-ba43-5d9277c6a929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thailand</value>
      <webElementGuid>2df82c17-4791-449c-b3c6-c90713226a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vfb-13-country-container&quot;)</value>
      <webElementGuid>195ab95c-6883-47b4-bedd-872c16ae36af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vfb-13-country-container']</value>
      <webElementGuid>b622f138-e123-462a-8fc1-6778c44d204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[6]/span/span/span/span</value>
      <webElementGuid>aaca39ca-1218-43cf-ab04-011ffbf7262f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::span[5]</value>
      <webElementGuid>b06f8c7b-9913-4be3-a184-5b98f5f4de66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State / Province / Region'])[1]/following::span[6]</value>
      <webElementGuid>8b473bab-a07e-40f3-a6e9-965f537d5c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[3]</value>
      <webElementGuid>22a44b62-3331-41b2-9899-aeb399e79078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/span/span/span/span</value>
      <webElementGuid>921e8523-9f0d-489b-9bf7-269c86b380b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vfb-13-country-container' and @title = 'Thailand' and (text() = 'Thailand' or . = 'Thailand')]</value>
      <webElementGuid>70b58348-7105-4dfe-a2a0-e939cabecea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
